# Generated by Django 6.0.5 on 2026-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your hero background images (WebP)', upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which they appear')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload your logo (WebP or PNG)', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload your favicon (ICO or PNG)', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
