# Generated by Django 6.0.5 on 2026-05-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_heroimage_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='highlight_text',
            field=models.CharField(default='Locally Made', help_text="Middle highlighted/outlined text (e.g., 'Locally Made')", max_length=100),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='text_line_1',
            field=models.CharField(default='Authentic', help_text="First line of text (e.g., 'Authentic')", max_length=100),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='text_line_3',
            field=models.CharField(default='Furniture.', help_text="Bottom line of text (e.g., 'Furniture.')", max_length=100),
        ),
    ]
