# Generated by Django 6.0.5 on 2026-05-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_heroimage_highlight_text_heroimage_text_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='room_area',
            field=models.CharField(blank=True, help_text='e.g. Master Bedroom', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_transition_seconds',
            field=models.PositiveIntegerField(default=7, help_text='Number of seconds each hero image stays on screen'),
        ),
    ]
