# Generated by Django 6.0.5 on 2026-05-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_adminnotification_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteInspirationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Client inspiration images', upload_to='quote_inspirations/')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_images', to='inventory.quoterequest')),
            ],
        ),
    ]
