# Generated by Django 6.0.5 on 2026-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_quoteinspirationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
